language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

before_script: composer install

script:
  - phpunit --configuration build/phpunit.xml

notifications:
  slack: clearidea:UL7PtI529f0u9rcGW108IoE0
